datasource:
  workspace: nmlProducts
  namespaces:
    mt: https://www.magnolia-travel.com/jcr/1.0/mt
  autoCreate: true

model:
  nodeType: mt:nmlProduct
  properties:
    - name: product_id
    - name: product_name
    - name: product_img_link
      type: asset
    - name: mediaContents
      type: mediaContent
      multiple: true
  subModels:
    - name: mediaContent
      properties:
        - name: caption
        - name: vimeoLink
        - name: imageLink
          type: asset
        